# [optional] to set up a HARBOR, and to integrate the HARBOR with k8s cluster
# read the guide: 'guide/harbor.md'

- hosts: harbor
  #这一步是安装harbor
  roles:
  - { role: chrony, when: "NEW_INSTALL == 'yes' and groups['chrony']|length > 0" }
  - { role: prepare, when: "NEW_INSTALL == 'yes'" }
  - { role: docker, when: "NEW_INSTALL == 'yes'" }
  - { role: harbor, when: "NEW_INSTALL == 'yes'" } 
  tasks:
  - name: Fetching the HARBOR SERVER's CA cert
    fetch:
      src: "{{ ca_dir }}/ca.pem"
      dest: "{{ base_dir }}/down/"
      flat: yes
    when: hostvars[groups.harbor[0]]['SELF_SIGNED_CERT'] == 'yes' #如果是自签名，那么复制ca的证书到/etc/ansible/down下面

- hosts: 
  - kube-master
  - kube-node
  tasks:
  - name: Define 'harbor_hostname', a domain name
    set_fact: harbor_hostname={{ hostvars[groups.harbor[0]]['HARBOR_DOMAIN'] }}

  - name: Define 'harbor_hostname', an IP Addr
    set_fact: harbor_hostname={{ groups['harbor'][0] }}
    when: hostvars[groups.harbor[0]]['HARBOR_DOMAIN'] == '' #如果HARBOR_DOMAIN没有定义，那么设置harbor_hostname 为harbor的ip地址。
  
  - block:  
      - block:  
        - name: Creating cert dir for the docker daemon
          file: name=/etc/docker/certs.d/{{ harbor_hostname }} state=directory #创建ca证书的目录
    
        - name: Installing the HARBOR SERVER's CA cert for docker
          copy: src={{ base_dir }}/down/ca.pem dest=/etc/docker/certs.d/{{ harbor_hostname }}/ca.crt #复制ca的证书到证书目录
        when: CONTAINER_RUNTIME == 'docker'

      - block:  
        - name: Installing the HARBOR SERVER's CA cert on k8s nodes
          copy: src={{ base_dir }}/down/ca.pem dest=/usr/share/ca-certificates/harbor-ca.crt

        - name: Add the HARBOR SERVER's CA cert 
          lineinfile:
            dest: /etc/ca-certificates.conf
            state: present
            regexp: 'harbor-ca'
            line: 'harbor-ca.crt'

        - name: Update the trusted ca-certificates
          shell: 'update-ca-certificates'

        - name: restart containerd
          service: name=containerd state=restarted
        when:
        - 'CONTAINER_RUNTIME == "containerd"'
        - 'ansible_distribution == "Ubuntu"'

      - block:  
        - name: Installing the HARBOR SERVER's CA cert on k8s nodes
          copy: src={{ base_dir }}/down/ca.pem dest=/etc/pki/ca-trust/source/anchors/harbor-ca.crt

        - name: Update the trusted ca-certificates
          shell: 'update-ca-trust'

        - name: restart containerd
          service: name=containerd state=restarted
        when:
        - 'CONTAINER_RUNTIME == "containerd"'
        - 'ansible_distribution in ["CentOS","RedHat","Amazon"]'
    when: hostvars[groups.harbor[0]]['SELF_SIGNED_CERT'] == 'yes' # 自签名做的操作

  # [optional] if you have a DNS server, add an 'A record' instead
  - name: Adding an '/etc/hosts' entry for the HARBOR DOMAIN #在/etc/hosts中添加DNS记录
    lineinfile:
      dest: /etc/hosts
      state: present
      regexp: '{{ harbor_hostname }}'
      line: "{{ groups['harbor'][0] }} {{ harbor_hostname }}"
    when: "hostvars[groups.harbor[0]]['HARBOR_DOMAIN'] != ''" #如果制定了HARBOR_DOMAIN的话，否则就直接使用ip地址
    ignore_errors: true
  
  # [optional] 使用 cloud-init 初始化的虚拟机，/etc/hosts 后会重启时被替换，需修改对应的模板文件 
  - name: Adding cloud-init hosts template (debian) entry for the HARBOR DOMAIN
    lineinfile:
      dest: /etc/cloud/templates/hosts.debian.tmpl
      state: present
      regexp: '{{ harbor_hostname }}'
      line: "{{ groups['harbor'][0] }} {{ harbor_hostname }}"
    when: 'ansible_distribution in ["Ubuntu","Debian"]'
    ignore_errors: true


  - name: Adding cloud-init hosts template (redhat) entry for the HARBOR DOMAIN
    lineinfile:
      dest: /etc/cloud/templates/hosts.redhat.tmpl
      state: present
      regexp: '{{ harbor_hostname }}'
      line: "{{ groups['harbor'][0] }} {{ harbor_hostname }}"
    when: 'ansible_distribution in ["CentOS","RedHat","Amazon"]' 
    ignore_errors: true
